In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import matplotlib
from sklearn.impute import KNNImputer
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import precision_score,recall_score,f1_score,cohen_kappa_score
import statsmodels.api as sm
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import cross_val_score
import pylab as pl
pd.options.display.max_rows=None
pd.options.display.max_columns=None
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#df1 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Final_Cleaned.csv')
df1 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Final_Cleaned.csv')

In [ ]:
df=df1[['Unnamed: 0.1.1',
'loan_amnt',
'term',
'int_rate',
'installment',
'sub_grade',
'home_ownership',
'annual_inc',
'verification_status',
'purpose',
'delinq_2yrs',
'open_acc',
'pub_rec',
'revol_bal',
'total_acc',
'initial_list_status',
'out_prncp',
'total_pymnt',
'total_rec_prncp',
'total_rec_int',
'total_rec_late_fee',
'last_pymnt_amnt',
'application_type',
'tot_coll_amt',
'tot_cur_bal',
'open_acc_6m',
'open_act_il',
'open_il_12m',
'open_il_24m',
'total_bal_il',
'open_rv_12m',
'open_rv_24m',
'max_bal_bc',
'total_rev_hi_lim',
'inq_fi',
'total_cu_tl',
'inq_last_12m',
'acc_open_past_24mths',
'mo_sin_old_rev_tl_op',
'mo_sin_rcnt_rev_tl_op',
'mo_sin_rcnt_tl',
'mort_acc',
'num_accts_ever_120_pd',
'num_actv_bc_tl',
'num_actv_rev_tl',
'num_bc_sats',
'num_bc_tl',
'num_il_tl',
'num_op_rev_tl',
'num_rev_accts',
'num_rev_tl_bal_gt_0',
'num_sats',
'num_tl_op_past_12m',
'pub_rec_bankruptcies',
'tot_hi_cred_lim',
'total_bal_ex_mort',
'total_bc_limit',
'total_il_high_credit_limit',
'disbursement_method',
'loan_status',
'il_util',
'mths_since_recent_inq',
'mths_since_rcnt_il',
'mo_sin_old_il_acct',
'bc_util',
'percent_bc_gt_75',
'bc_open_to_buy',
'mths_since_recent_bc',
'dti',
'revol_util',
'all_util',
'avg_cur_bal',
'pct_tl_nvr_dlq']]

In [ ]:
df_c = df.copy(deep=True)

In [ ]:
df_c = df_c.rename({'Unnamed: 0.1.1':'ID'}, axis=1)

In [ ]:
df_c.head(2)

ID  loan_amnt        term  int_rate  installment sub_grade  \
0  343481  71.310442   36 months  2.794780    18.386629        D2   
1  343482  87.134314   60 months  3.107894    21.092636        E5   

  home_ownership  annual_inc verification_status             purpose  \
0           RENT   76.282376     Source Verified  debt_consolidation   
1       MORTGAGE   74.441265            Verified  debt_consolidation   

   delinq_2yrs  open_acc  pub_rec  revol_bal  total_acc initial_list_status  \
0            1  3.493362        0  21.086054   5.252012                   w   
1            0  4.147580        0  54.144615   7.973929                   w   

    out_prncp  total_pymnt  total_rec_prncp  total_rec_int  \
0   77.234847    15.828322        12.196131      28.918987   
1  100.229002    17.444102        11.711664      41.597367   

   total_rec_late_fee  last_pymnt_amnt application_type  tot_coll_amt  \
0                 0.0         4.563472        Joint App             0   
1                 0.0         4.757724       Individual             0   

   tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
0    43.413863            3            1            2            3   
1    61.236392            1           15            0            0   

   total_bal_il  open_rv_12m  open_rv_24m  max_bal_bc  total_rev_hi_lim  \
0     65.932533            1            5   22.451932         37.714065   
1    112.009436            2            4   82.265507         40.381219   

   inq_fi  total_cu_tl  inq_last_12m  acc_open_past_24mths  \
0       2            4             2              3.085858   
1       0            1             1              1.969564   

   mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  mo_sin_rcnt_tl  mort_acc  \
0             14.460281               1.077967        1.068123         2   
1             13.939855               1.077967        1.068123         2   

   num_accts_ever_120_pd  num_actv_bc_tl  num_actv_rev_tl  num_bc_sats  \
0                      1        1.567930         2.060831     1.513386   
1                      0        1.857586         2.447468     1.782384   

   num_bc_tl  num_il_tl  num_op_rev_tl  num_rev_accts  num_rev_tl_bal_gt_0  \
0   2.028252   2.539273       2.900628       3.205608             2.088951   
1   2.954972   5.117636       2.296616       3.286357             2.486553   

   num_sats  num_tl_op_past_12m  pub_rec_bankruptcies  tot_hi_cred_lim  \
0  3.487390            1.427368                     0        35.191359   
1  4.139374            1.124303                     0        45.366029   

   total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  \
0          54.301766       60.262431                   90.793486   
1          91.225286       82.316757                  156.824990   

  disbursement_method  loan_status     il_util  mths_since_recent_inq  \
0                Cash            0  111.115238               1.315541   
1                Cash            0  129.420802               0.000000   

   mths_since_rcnt_il  mo_sin_old_il_acct    bc_util  percent_bc_gt_75  \
0            1.054226           76.777401   4.840865          0.000000   
1            3.159992           84.409140  29.974483          6.091383   

   bc_open_to_buy  mths_since_recent_bc       dti  revol_util    all_util  \
0       30.442814              1.082148  3.575261    2.888863   49.177635   
1       26.242790              1.082148  4.041209   24.150069  100.424977   

   avg_cur_bal  pct_tl_nvr_dlq  
0    17.857692    5.435560e+21  
1    22.452351    8.641666e+21

In [ ]:
df_c = df_c.set_index('ID')

In [ ]:
df_c.head(2)

loan_amnt        term  int_rate  installment sub_grade home_ownership  \
ID                                                                              
343481  71.310442   36 months  2.794780    18.386629        D2           RENT   
343482  87.134314   60 months  3.107894    21.092636        E5       MORTGAGE   

        annual_inc verification_status             purpose  delinq_2yrs  \
ID                                                                        
343481   76.282376     Source Verified  debt_consolidation            1   
343482   74.441265            Verified  debt_consolidation            0   

        open_acc  pub_rec  revol_bal  total_acc initial_list_status  \
ID                                                                    
343481  3.493362        0  21.086054   5.252012                   w   
343482  4.147580        0  54.144615   7.973929                   w   

         out_prncp  total_pymnt  total_rec_prncp  total_rec_int  \
ID                                                                
343481   77.234847    15.828322        12.196131      28.918987   
343482  100.229002    17.444102        11.711664      41.597367   

        total_rec_late_fee  last_pymnt_amnt application_type  tot_coll_amt  \
ID                                                                           
343481                 0.0         4.563472        Joint App             0   
343482                 0.0         4.757724       Individual             0   

        tot_cur_bal  open_acc_6m  open_act_il  open_il_12m  open_il_24m  \
ID                                                                        
343481    43.413863            3            1            2            3   
343482    61.236392            1           15            0            0   

        total_bal_il  open_rv_12m  open_rv_24m  max_bal_bc  total_rev_hi_lim  \
ID                                                                             
343481     65.932533            1            5   22.451932         37.714065   
343482    112.009436            2            4   82.265507         40.381219   

        inq_fi  total_cu_tl  inq_last_12m  acc_open_past_24mths  \
ID                                                                
343481       2            4             2              3.085858   
343482       0            1             1              1.969564   

        mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  mo_sin_rcnt_tl  mort_acc  \
ID                                                                              
343481             14.460281               1.077967        1.068123         2   
343482             13.939855               1.077967        1.068123         2   

        num_accts_ever_120_pd  num_actv_bc_tl  num_actv_rev_tl  num_bc_sats  \
ID                                                                            
343481                      1        1.567930         2.060831     1.513386   
343482                      0        1.857586         2.447468     1.782384   

        num_bc_tl  num_il_tl  num_op_rev_tl  num_rev_accts  \
ID                                                           
343481   2.028252   2.539273       2.900628       3.205608   
343482   2.954972   5.117636       2.296616       3.286357   

        num_rev_tl_bal_gt_0  num_sats  num_tl_op_past_12m  \
ID                                                          
343481             2.088951  3.487390            1.427368   
343482             2.486553  4.139374            1.124303   

        pub_rec_bankruptcies  tot_hi_cred_lim  total_bal_ex_mort  \
ID                                                                 
343481                     0        35.191359          54.301766   
343482                     0        45.366029          91.225286   

        total_bc_limit  total_il_high_credit_limit disbursement_method  \
ID                                                                       
343481       60.262431                   90.793486                C

In [ ]:
df_c.isnull().sum()

loan_amnt                     0
term                          0
int_rate                      0
installment                   0
sub_grade                     0
home_ownership                0
annual_inc                    0
verification_status           0
purpose                       0
delinq_2yrs                   0
open_acc                      0
pub_rec                       0
revol_bal                     0
total_acc                     0
initial_list_status           0
out_prncp                     0
total_pymnt                   0
total_rec_prncp               0
total_rec_int                 0
total_rec_late_fee            0
last_pymnt_amnt               0
application_type              0
tot_coll_amt                  0
tot_cur_bal                   0
open_acc_6m                   0
open_act_il                   0
open_il_12m                   0
open_il_24m                   0
total_bal_il                  0
open_rv_12m                   0
open_rv_24m                   0
max_bal_

In [ ]:
df_c = pd.get_dummies(df_c,drop_first=True)

In [ ]:
X1=df_c.drop('loan_status',axis=1)

In [ ]:
y1 = df_c[['loan_status']]

In [ ]:
x_train, X, y_train, y = train_test_split(X1, y1,
                                                    test_size=0.50,
                                                    random_state=10,
                                                    stratify=y1)


In [ ]:
X.shape

(75396, 118)

In [ ]:
y.shape

(75396, 1)

Model 1.1 - Logistic Regression

In [ ]:
lr = LogisticRegression()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .20,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
lr.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(lr.score(Xtrain,ytrain))
print("Testing Accuracy")
print(lr.score(scaledXtest,ytest))
scoreslr = cross_val_score(lr, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoreslr))
predictedlr = lr.predict(scaledXtest)
print(confusion_matrix(ytest,predictedlr))
print(classification_report(ytest,predictedlr))

Training Accuracy
0.9383082432522051
Testing Accuracy
0.9768567639257294
Cross Validation Accuracy
0.9508945812065365
[[14136    15]
 [  334   595]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     14151
           1       0.98      0.64      0.77       929

    accuracy                           0.98     15080
   macro avg       0.98      0.82      0.88     15080
weighted avg       0.98      0.98      0.97     15080



Model 1.2 - Decision Tree Classifier

In [ ]:
dt = DecisionTreeClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .20,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
dt.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(dt.score(Xtrain,ytrain))
print("Testing Accuracy")
print(dt.score(scaledXtest,ytest))
scoresdt = cross_val_score(dt, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresdt))
predicted_dt = dt.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_dt))
print(classification_report(ytest,predicted_dt))

Training Accuracy
0.7189303004177996
Testing Accuracy
0.9611405835543767
Cross Validation Accuracy
0.8437272469663183
[[13849   302]
 [  284   645]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98     14151
           1       0.68      0.69      0.69       929

    accuracy                           0.96     15080
   macro avg       0.83      0.84      0.83     15080
weighted avg       0.96      0.96      0.96     15080



Model 1.3 - RandomForestClassifier

In [ ]:
rf = RandomForestClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
rf.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(rf.score(Xtrain,ytrain))
print("Testing Accuracy")
print(rf.score(scaledXtest,ytest))
scoresrf = cross_val_score(rf, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresrf))
predicted_rf = rf.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_rf))
print(classification_report(ytest,predicted_rf))

Training Accuracy
0.9388180457396215
Testing Accuracy
0.9694504620009726
Cross Validation Accuracy
0.9281628021933047
[[21208     5]
 [  686   720]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     21213
           1       0.99      0.51      0.68      1406

    accuracy                           0.97     22619
   macro avg       0.98      0.76      0.83     22619
weighted avg       0.97      0.97      0.96     22619



Model 1.4- Naive Bayes Theorem

In [ ]:
gnb = GaussianNB()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
gnb.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(gnb.score(Xtrain,ytrain))
print("Testing Accuracy")
print(gnb.score(scaledXtest,ytest))
scoresgnb = cross_val_score(gnb, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresgnb))
predicted_gnb = gnb.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_gnb))
print(classification_report(ytest,predicted_gnb))

Training Accuracy
0.06146616897512174
Testing Accuracy
0.11866130244484725
Cross Validation Accuracy
0.7085129849099125
[[ 1294 19919]
 [   16  1390]]
              precision    recall  f1-score   support

           0       0.99      0.06      0.11     21213
           1       0.07      0.99      0.12      1406

    accuracy                           0.12     22619
   macro avg       0.53      0.52      0.12     22619
weighted avg       0.93      0.12      0.12     22619



Model 1.5- KNN CLassifier

In [ ]:
knn = KNeighborsClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
knn.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(knn.score(Xtrain,ytrain))
print("Testing Accuracy")
print(knn.score(scaledXtest,ytest))
scoresknn = cross_val_score(knn, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresknn))
predicted_knn = knn.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_knn))
print(classification_report(ytest,predicted_knn))

Training Accuracy
0.9385338310248783
Testing Accuracy
0.9390335558601176
Cross Validation Accuracy
0.6465639526973089
[[21161    52]
 [ 1327    79]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97     21213
           1       0.60      0.06      0.10      1406

    accuracy                           0.94     22619
   macro avg       0.77      0.53      0.54     22619
weighted avg       0.92      0.94      0.91     22619



Model 1.6- GradientBoosting Classifier

In [ ]:
gbc = GradientBoostingClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
gbc.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(gbc.score(Xtrain,ytrain))
print("Testing Accuracy")
print(gbc.score(scaledXtest,ytest))
scoresgbc = cross_val_score(gbc, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresgbc))
predicted_gbc = gbc.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_gbc))
print(classification_report(ytest,predicted_gbc))

Training Accuracy
0.8428103150993804
Testing Accuracy
0.9751094212829922
Cross Validation Accuracy
0.9504820788017293
[[21191    22]
 [  541   865]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     21213
           1       0.98      0.62      0.75      1406

    accuracy                           0.98     22619
   macro avg       0.98      0.81      0.87     22619
weighted avg       0.98      0.98      0.97     22619



Model 1.7 - AdaBoostClassifer

In [ ]:
ad = AdaBoostClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
ad.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(ad.score(Xtrain,ytrain))
print("Testing Accuracy")
print(ad.score(scaledXtest,ytest))
scoresgad = cross_val_score(ad, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresgad))
predicted_ad = ad.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_ad))
print(classification_report(ytest,predicted_ad))

Training Accuracy
0.9385527786725278
Testing Accuracy
0.970555727485742
Cross Validation Accuracy
0.9364948944267178
[[21162    51]
 [  615   791]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     21213
           1       0.94      0.56      0.70      1406

    accuracy                           0.97     22619
   macro avg       0.96      0.78      0.84     22619
weighted avg       0.97      0.97      0.97     22619



Model 1.8 - XGBoostClassifier

In [ ]:
xgb = XGBClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
xgb.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(xgb.score(scaledXtrain,ytrain))
print("Testing Accuracy")
print(xgb.score(scaledXtest,ytest))
scoresxgb = cross_val_score(xgb, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresxgb))
predicted_xgb = xgb.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_xgb))
print(classification_report(ytest,predicted_xgb))

Training Accuracy
0.9772438751728972
Testing Accuracy
0.9745788938503028
Cross Validation Accuracy
0.9511038879044531
[[21202    11]
 [  564   842]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99     21213
           1       0.99      0.60      0.75      1406

    accuracy                           0.97     22619
   macro avg       0.98      0.80      0.87     22619
weighted avg       0.97      0.97      0.97     22619



1.9 Support Vector Classifier

In [ ]:
from sklearn.svm import SVC 
svc = SVC()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
svc.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(svc.score(scaledXtrain,ytrain))
print("Testing Accuracy")
print(svc.score(scaledXtest,ytest))
scoressvc = cross_val_score(svc, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoressvc))
predicted_svc = svc.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_svc))
print(classification_report(ytest,predicted_svc))

Training Accuracy
0.9731322356329462
Testing Accuracy
0.9681241434192494
Cross Validation Accuracy
0.9382050631290783
[[21202    11]
 [  710   696]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98     21213
           1       0.98      0.50      0.66      1406

    accuracy                           0.97     22619
   macro avg       0.98      0.75      0.82     22619
weighted avg       0.97      0.97      0.96     22619

